apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.deployment.name }}

spec:

  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  template:

    metadata:
      labels:
        app: {{ .Values.app.name }}

    spec:
      containers:

        - name: {{ .Values.app.name }}
          image: "{{ .Values.deployment.image }}"
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          env:
            - name: MYSQL_DB_URL
              value: {{ .Values.db.url }}
            - name: MYSQL_DB_NAME
              value: {{ .Values.db.name }}
            - name: MYSQL_USER
              value: {{ .Values.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.db.password }}
          resources:
            requests:
              cpu: {{ .Values.deployment.cpu }}