apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.deployment.name }}

spec:

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}

  replicas: {{ .Values.deployment.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  template:

    metadata:
      labels:
        app: {{ .Values.app.name }}

    spec:
      containers:

        - name: {{ .Values.app.name }}
          image: "{{ .Values.deployment.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.deployment.httpPort }}
            - name: jmx
              containerPort: {{ .Values.deployment.jmxPort }}
          env:
            - name: MYSQL_DB_URL
              value: {{ .Values.db.url }}
            - name: MYSQL_DB_NAME
              value: {{ .Values.db.name }}
            - name: MYSQL_USER
              value: {{ .Values.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.db.password }}
          resources:
            requests:
              cpu: {{ .Values.deployment.requests.cpu }}
              memory: {{ .Values.deployment.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.limits.cpu }}
              memory: {{ .Values.deployment.limits.memory }}
          readinessProbe:
            enabled: true
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.deployment.readinessProbe.httpGet.path }}
              port: {{ .Values.deployment.readinessProbe.httpGet.port }}
