---
apiVersion: v1
kind: Service

metadata: 
  name: {{ .Values.service.name }}
  
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.jmx_service.name }}

spec:
  type: {{ .Values.jmx_service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: {{ .Values.jmx_service.port }}
      targetPort: {{ .Values.jmx_service.targetPort }}
      nodePort: {{ .Values.jmx_service.nodePort }}