---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.petclinic.name }}-deployment
spec:
  replicas: {{ .Values.petclinic.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.petclinic.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.petclinic.name }}
    spec:
      containers:
        - name: {{ .Values.petclinic.name }}
          image: {{ .Values.petclinic.deployment.image }}
          ports:
            - containerPort: {{ .Values.petclinic.deployment.containerPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.petclinic.name }}-service
spec:
  type: {{ .Values.petclinic.service.type }}
  selector:
    app: {{ .Values.petclinic.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.petclinic.service.port }}
      targetPort: {{ .Values.petclinic.service.targetPort }}
