name: Main Branch Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      NEW_TAG: ${{ steps.new_version.outputs.new_tag }}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Get Current Version
        id: current_version
        run: |
          current_tag=$( (git ls-remote --tags --sort=v:refname origin | tail -1 | awk -F/ '{print $3}') || echo "" )
          if [[ "${current_tag}" == "" ]]; then
            current_tag="v0.0.0"
          fi
          echo "current_tag=${current_tag}" >> $GITHUB_OUTPUT

      - name: Get Next Version
        id: new_version
        run: |
          current_tag="${{ steps.current_version.outputs.current_tag }}"
          major=$( echo $current_tag | sed "s/[.][0-9]*[.][0-9]*//" | sed "s/v//" )
          minor=$( echo $current_tag | sed "s/v[0-9]*[.]//" | sed "s/[.][0-9]*//" )
          patch=$( echo $current_tag | sed "s/v[0-9]*[.][0-9]*[.]//" )
          minor=$((minor + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=${new_tag}" >> $GITHUB_OUTPUT

      - name: Add Tag
        run: |
          tag="${{ steps.new_version.outputs.new_tag }}"
          git tag $tag
          git push origin $tag

  staticAnalysis:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Sey Up JDK17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          
      - name: Static analysis
        run: ./gradlew checkstyleMain
        
      - name: Save Report
        uses: actions/upload-artifact@v4
        with:
          name: Static Analysis Report
          path: build/reports/checkstyle/checkstyle.html

  runTests:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Sey Up JDK17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          
      - name: Run Tests
        run: ./gradlew test
        
      - name: Save Report
        uses: actions/upload-artifact@v4
        with:
          name: Tests Report
          path: build/reports/tests/tests.html
          
  build:
    needs: [ "staticAnalysis", "runTests" ]
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Sey Up JDK17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          
      - name: Build
        run: ./gradlew build -x checkstyleMain -x test
        
      - name: Save .jar file
        uses: actions/upload-artifact@v4
        with:
          name: Spring Petclinic JAR
          path: build/libs/*.jar

  dockerImage:
    needs: [ "build", "version" ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: Spring Petclinic JAR
          path: ./petclinic.jar

      - name: Build Docker Image
        run: docker build -t spring-petclinic:${{ needs.version.outputs.NEW_TAG }} .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: spring-petclinic:${{ needs.version.outputs.NEW_TAG }}
          format: 'table'

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Push Docker image to GCP Artifact Registry
        run: |
          docker tag spring-petclinic:${{ needs.version.outputs.NEW_TAG }} ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT }}/${{ secrets.MAIN_REPO }}/spring-petclinic:${{ needs.version.outputs.NEW_TAG }}
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT }}/${{ secrets.MAIN_REPO }}/spring-petclinic:${{ needs.version.outputs.NEW_TAG }}
