name: Main Branch Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  version:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Get Current Version
        id: current_version
        run: |
          current_tag=$( git describe --tags --abbrev=0 2> /dev/null || echo "" )
          if [[ "${current_tag}" == "" ]]; then
            current_tag="v0.0.0"
          fi
          echo "current_tag=${current_tag}" >> $GITHUB_OUTPUT

      - name: Get Next Version
        id: next_version
        run: |
          current_tag="${{ steps.current_version.outputs.current_tag }}"
          major=$( echo $current_tag | sed "s/[.][0-9]*[.][0-9]*//" | sed "s/v//" )
          minor=$( echo $current_tag | sed "s/v[0-9]*[.]//" | sed "s/[.][0-9]*//" )
          patch=$( echo $current_tag | sed "s/v[0-9]*[.][0-9]*[.]//" )
          minor=$( minor + 1 )
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=${new_tag}"
