name: PR Pipeline

on:
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:

  staticAnalysis:
    runs-on: self-hosted
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Sey Up JDK17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          
      - name: Static analysis
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          ./gradlew checkstyleMain
        
      - name: Save Report
        uses: actions/upload-artifact@v4
        with:
          name: Static Analysis Report
          path: build/reports/checkstyle/checkstyle.html

  runTests:
      runs-on: self-hosted
      steps:
      
        - name: Checkout Code
          uses: actions/checkout@v5
          
        - name: Sey Up JDK17
          uses: actions/setup-java@v5
          with:
            distribution: temurin
            java-version: 17
            
        - name: Run Tests
          run: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            ./gradlew test
          
        - name: Save Report
          uses: actions/upload-artifact@v4
          with:
            name: Tests Report
            path: build/reports/tests/tests.html
          
  build:
      # needs: [ "staticAnalysis", "runTests" ]
      runs-on: self-hosted
      steps:
      
        - name: Checkout Code
          uses: actions/checkout@v5
          
        - name: Sey Up JDK17
          uses: actions/setup-java@v5
          with:
            distribution: temurin
            java-version: 17
            
        - name: Build
          run: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            ./gradlew build -x checkstyleMain -x test
          
        - name: Save .jar file
          uses: actions/upload-artifact@v4
          with:
            name: Spring Petclinic JAR
            path: build/libs/*.jar

  dockerImage:
    needs: [ "build" ]
    runs-on: self-hosted
    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: Spring Petclinic JAR
          path: ./petclinic.jar

      - name: Build Docker Image
        run: docker build -t spring-petclinic:${{ github.sha }} .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: spring-petclinic:${{ github.sha }}
          format: 'table'

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Push Docker image to GCP Artifact Registry
        run: |
          docker tag spring-petclinic:${{ github.sha }} ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT }}/${{ secrets.PR_REPO }}/spring-petclinic:${{ github.sha }}
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT }}/${{ secrets.PR_REPO }}/spring-petclinic:${{ github.sha }}
