name: PR Pipeline

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  staticAnalysis:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Sey Up JDK17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          
      - name: Static analysis
        run: ./gradlew checkstyleMain
        
      - name: Save Report
        uses: actions/upload-artifact@v4
        with:
          name: Static Analysis Report
          path: build/reports/checkstyle/checkstyle.html

  runTests:
      runs-on: ubuntu-latest
      steps:
      
        - name: Checkout Code
          uses: actions/checkout@v5
          
        - name: Sey Up JDK17
          uses: actions/setup-java@v5
          with:
            distribution: temurin
            java-version: 17
            
        - name: Run Tests
          run: ./gradlew test
          
        - name: Save Report
          uses: actions/upload-artifact@v4
          with:
            name: Tests Report
            path: build/reports/tests/tests.html
          
  build:
      needs: [ "staticAnalysis", "runTests" ]
      runs-on: ubuntu-latest
      steps:
      
        - name: Checkout Code
          uses: actions/checkout@v5
          
        - name: Sey Up JDK17
          uses: actions/setup-java@v5
          with:
            distribution: temurin
            java-version: 17
            
        - name: Build
          run: ./gradlew build -x checkstyleMain -x test
          
        - name: Save .jar file
          uses: actions/upload-artifact@v4
          with:
            name: Spring Petclinic JAR
            path: build/libs/*.jar

  dockerImage:
    needs: [ "build" ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: Spring Petclinic JAR
          path: ./petclinic.jar

      - name: Build Docker Image
        run: docker build -t spring-petclinic:latest .
